/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ArReservationRouteImport } from './routes/ar.reservation'
import { Route as ArQueueRouteImport } from './routes/ar.queue'
import { Route as ArProductsRouteImport } from './routes/ar.products'
import { Route as ArLoginRouteImport } from './routes/ar.login'
import { Route as ArAppRouteImport } from './routes/ar.app'
import { Route as AdminQueueDisplayRouteImport } from './routes/admin.queue-display'
import { Route as AdminQueueAnalyticsRouteImport } from './routes/admin.queue-analytics'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBarberWorkspaceRouteImport } from './routes/admin.barber-workspace'
import { Route as ArServicesIndexRouteImport } from './routes/ar.services.index'
import { Route as ArServicesSlugRouteImport } from './routes/ar.services.$slug'
import { Route as ArAdminQueueDisplayRouteImport } from './routes/ar.admin.queue-display'
import { Route as ArAdminQueueAnalyticsRouteImport } from './routes/ar.admin.queue-analytics'
import { Route as ArAdminQueueRouteImport } from './routes/ar.admin.queue'
import { Route as ArAdminBookingsRouteImport } from './routes/ar.admin.bookings'
import { Route as ArAdminBarberWorkspaceRouteImport } from './routes/ar.admin.barber-workspace'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArReservationRoute = ArReservationRouteImport.update({
  id: '/ar/reservation',
  path: '/ar/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArQueueRoute = ArQueueRouteImport.update({
  id: '/ar/queue',
  path: '/ar/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProductsRoute = ArProductsRouteImport.update({
  id: '/ar/products',
  path: '/ar/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ArLoginRoute = ArLoginRouteImport.update({
  id: '/ar/login',
  path: '/ar/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAppRoute = ArAppRouteImport.update({
  id: '/ar/app',
  path: '/ar/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueDisplayRoute = AdminQueueDisplayRouteImport.update({
  id: '/admin/queue-display',
  path: '/admin/queue-display',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueAnalyticsRoute = AdminQueueAnalyticsRouteImport.update({
  id: '/admin/queue-analytics',
  path: '/admin/queue-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBarberWorkspaceRoute = AdminBarberWorkspaceRouteImport.update({
  id: '/admin/barber-workspace',
  path: '/admin/barber-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ArServicesIndexRoute = ArServicesIndexRouteImport.update({
  id: '/ar/services/',
  path: '/ar/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArServicesSlugRoute = ArServicesSlugRouteImport.update({
  id: '/ar/services/$slug',
  path: '/ar/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAdminQueueDisplayRoute = ArAdminQueueDisplayRouteImport.update({
  id: '/ar/admin/queue-display',
  path: '/ar/admin/queue-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAdminQueueAnalyticsRoute = ArAdminQueueAnalyticsRouteImport.update({
  id: '/ar/admin/queue-analytics',
  path: '/ar/admin/queue-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAdminQueueRoute = ArAdminQueueRouteImport.update({
  id: '/ar/admin/queue',
  path: '/ar/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAdminBookingsRoute = ArAdminBookingsRouteImport.update({
  id: '/ar/admin/bookings',
  path: '/ar/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAdminBarberWorkspaceRoute = ArAdminBarberWorkspaceRouteImport.update({
  id: '/ar/admin/barber-workspace',
  path: '/ar/admin/barber-workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reservation': typeof ReservationRoute
  '/admin/barber-workspace': typeof AdminBarberWorkspaceRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/queue-analytics': typeof AdminQueueAnalyticsRoute
  '/admin/queue-display': typeof AdminQueueDisplayRoute
  '/ar/app': typeof ArAppRoute
  '/ar/login': typeof ArLoginRoute
  '/ar/products': typeof ArProductsRoute
  '/ar/queue': typeof ArQueueRoute
  '/ar/reservation': typeof ArReservationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ar/': typeof ArIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ar/admin/barber-workspace': typeof ArAdminBarberWorkspaceRoute
  '/ar/admin/bookings': typeof ArAdminBookingsRoute
  '/ar/admin/queue': typeof ArAdminQueueRoute
  '/ar/admin/queue-analytics': typeof ArAdminQueueAnalyticsRoute
  '/ar/admin/queue-display': typeof ArAdminQueueDisplayRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/services/': typeof ArServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reservation': typeof ReservationRoute
  '/admin/barber-workspace': typeof AdminBarberWorkspaceRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/queue-analytics': typeof AdminQueueAnalyticsRoute
  '/admin/queue-display': typeof AdminQueueDisplayRoute
  '/ar/app': typeof ArAppRoute
  '/ar/login': typeof ArLoginRoute
  '/ar/products': typeof ArProductsRoute
  '/ar/queue': typeof ArQueueRoute
  '/ar/reservation': typeof ArReservationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ar': typeof ArIndexRoute
  '/services': typeof ServicesIndexRoute
  '/ar/admin/barber-workspace': typeof ArAdminBarberWorkspaceRoute
  '/ar/admin/bookings': typeof ArAdminBookingsRoute
  '/ar/admin/queue': typeof ArAdminQueueRoute
  '/ar/admin/queue-analytics': typeof ArAdminQueueAnalyticsRoute
  '/ar/admin/queue-display': typeof ArAdminQueueDisplayRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/services': typeof ArServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reservation': typeof ReservationRoute
  '/admin/barber-workspace': typeof AdminBarberWorkspaceRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/queue-analytics': typeof AdminQueueAnalyticsRoute
  '/admin/queue-display': typeof AdminQueueDisplayRoute
  '/ar/app': typeof ArAppRoute
  '/ar/login': typeof ArLoginRoute
  '/ar/products': typeof ArProductsRoute
  '/ar/queue': typeof ArQueueRoute
  '/ar/reservation': typeof ArReservationRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ar/': typeof ArIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ar/admin/barber-workspace': typeof ArAdminBarberWorkspaceRoute
  '/ar/admin/bookings': typeof ArAdminBookingsRoute
  '/ar/admin/queue': typeof ArAdminQueueRoute
  '/ar/admin/queue-analytics': typeof ArAdminQueueAnalyticsRoute
  '/ar/admin/queue-display': typeof ArAdminQueueDisplayRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/services/': typeof ArServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/products'
    | '/queue'
    | '/reservation'
    | '/admin/barber-workspace'
    | '/admin/bookings'
    | '/admin/queue'
    | '/admin/queue-analytics'
    | '/admin/queue-display'
    | '/ar/app'
    | '/ar/login'
    | '/ar/products'
    | '/ar/queue'
    | '/ar/reservation'
    | '/services/$slug'
    | '/ar/'
    | '/services/'
    | '/ar/admin/barber-workspace'
    | '/ar/admin/bookings'
    | '/ar/admin/queue'
    | '/ar/admin/queue-analytics'
    | '/ar/admin/queue-display'
    | '/ar/services/$slug'
    | '/ar/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/products'
    | '/queue'
    | '/reservation'
    | '/admin/barber-workspace'
    | '/admin/bookings'
    | '/admin/queue'
    | '/admin/queue-analytics'
    | '/admin/queue-display'
    | '/ar/app'
    | '/ar/login'
    | '/ar/products'
    | '/ar/queue'
    | '/ar/reservation'
    | '/services/$slug'
    | '/ar'
    | '/services'
    | '/ar/admin/barber-workspace'
    | '/ar/admin/bookings'
    | '/ar/admin/queue'
    | '/ar/admin/queue-analytics'
    | '/ar/admin/queue-display'
    | '/ar/services/$slug'
    | '/ar/services'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/products'
    | '/queue'
    | '/reservation'
    | '/admin/barber-workspace'
    | '/admin/bookings'
    | '/admin/queue'
    | '/admin/queue-analytics'
    | '/admin/queue-display'
    | '/ar/app'
    | '/ar/login'
    | '/ar/products'
    | '/ar/queue'
    | '/ar/reservation'
    | '/services/$slug'
    | '/ar/'
    | '/services/'
    | '/ar/admin/barber-workspace'
    | '/ar/admin/bookings'
    | '/ar/admin/queue'
    | '/ar/admin/queue-analytics'
    | '/ar/admin/queue-display'
    | '/ar/services/$slug'
    | '/ar/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  QueueRoute: typeof QueueRoute
  ReservationRoute: typeof ReservationRoute
  AdminBarberWorkspaceRoute: typeof AdminBarberWorkspaceRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminQueueAnalyticsRoute: typeof AdminQueueAnalyticsRoute
  AdminQueueDisplayRoute: typeof AdminQueueDisplayRoute
  ArAppRoute: typeof ArAppRoute
  ArLoginRoute: typeof ArLoginRoute
  ArProductsRoute: typeof ArProductsRoute
  ArQueueRoute: typeof ArQueueRoute
  ArReservationRoute: typeof ArReservationRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ArIndexRoute: typeof ArIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ArAdminBarberWorkspaceRoute: typeof ArAdminBarberWorkspaceRoute
  ArAdminBookingsRoute: typeof ArAdminBookingsRoute
  ArAdminQueueRoute: typeof ArAdminQueueRoute
  ArAdminQueueAnalyticsRoute: typeof ArAdminQueueAnalyticsRoute
  ArAdminQueueDisplayRoute: typeof ArAdminQueueDisplayRoute
  ArServicesSlugRoute: typeof ArServicesSlugRoute
  ArServicesIndexRoute: typeof ArServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/reservation': {
      id: '/ar/reservation'
      path: '/ar/reservation'
      fullPath: '/ar/reservation'
      preLoaderRoute: typeof ArReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/queue': {
      id: '/ar/queue'
      path: '/ar/queue'
      fullPath: '/ar/queue'
      preLoaderRoute: typeof ArQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products': {
      id: '/ar/products'
      path: '/ar/products'
      fullPath: '/ar/products'
      preLoaderRoute: typeof ArProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/login': {
      id: '/ar/login'
      path: '/ar/login'
      fullPath: '/ar/login'
      preLoaderRoute: typeof ArLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/app': {
      id: '/ar/app'
      path: '/ar/app'
      fullPath: '/ar/app'
      preLoaderRoute: typeof ArAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue-display': {
      id: '/admin/queue-display'
      path: '/admin/queue-display'
      fullPath: '/admin/queue-display'
      preLoaderRoute: typeof AdminQueueDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue-analytics': {
      id: '/admin/queue-analytics'
      path: '/admin/queue-analytics'
      fullPath: '/admin/queue-analytics'
      preLoaderRoute: typeof AdminQueueAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/barber-workspace': {
      id: '/admin/barber-workspace'
      path: '/admin/barber-workspace'
      fullPath: '/admin/barber-workspace'
      preLoaderRoute: typeof AdminBarberWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/services/': {
      id: '/ar/services/'
      path: '/ar/services'
      fullPath: '/ar/services/'
      preLoaderRoute: typeof ArServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/services/$slug': {
      id: '/ar/services/$slug'
      path: '/ar/services/$slug'
      fullPath: '/ar/services/$slug'
      preLoaderRoute: typeof ArServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/admin/queue-display': {
      id: '/ar/admin/queue-display'
      path: '/ar/admin/queue-display'
      fullPath: '/ar/admin/queue-display'
      preLoaderRoute: typeof ArAdminQueueDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/admin/queue-analytics': {
      id: '/ar/admin/queue-analytics'
      path: '/ar/admin/queue-analytics'
      fullPath: '/ar/admin/queue-analytics'
      preLoaderRoute: typeof ArAdminQueueAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/admin/queue': {
      id: '/ar/admin/queue'
      path: '/ar/admin/queue'
      fullPath: '/ar/admin/queue'
      preLoaderRoute: typeof ArAdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/admin/bookings': {
      id: '/ar/admin/bookings'
      path: '/ar/admin/bookings'
      fullPath: '/ar/admin/bookings'
      preLoaderRoute: typeof ArAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/admin/barber-workspace': {
      id: '/ar/admin/barber-workspace'
      path: '/ar/admin/barber-workspace'
      fullPath: '/ar/admin/barber-workspace'
      preLoaderRoute: typeof ArAdminBarberWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  QueueRoute: QueueRoute,
  ReservationRoute: ReservationRoute,
  AdminBarberWorkspaceRoute: AdminBarberWorkspaceRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminQueueAnalyticsRoute: AdminQueueAnalyticsRoute,
  AdminQueueDisplayRoute: AdminQueueDisplayRoute,
  ArAppRoute: ArAppRoute,
  ArLoginRoute: ArLoginRoute,
  ArProductsRoute: ArProductsRoute,
  ArQueueRoute: ArQueueRoute,
  ArReservationRoute: ArReservationRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ArIndexRoute: ArIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ArAdminBarberWorkspaceRoute: ArAdminBarberWorkspaceRoute,
  ArAdminBookingsRoute: ArAdminBookingsRoute,
  ArAdminQueueRoute: ArAdminQueueRoute,
  ArAdminQueueAnalyticsRoute: ArAdminQueueAnalyticsRoute,
  ArAdminQueueDisplayRoute: ArAdminQueueDisplayRoute,
  ArServicesSlugRoute: ArServicesSlugRoute,
  ArServicesIndexRoute: ArServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
