// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oogwfqnrgdvngifycdxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZ3dmcW5yZ2R2bmdpZnljZHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTAzMjQsImV4cCI6MjA5MTEyNjMyNH0.Wfe1D-pCru2a6p-GDyvKK7ey29i0VSNdoqqZhTrYL8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});